import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';import {spawnSync} from 'node:child_process';import {publicationInputs} from './verify-publications.mjs';
function fixture(t){
 const root=fs.mkdtempSync(path.join(tmpdir(),'publication-inputs-')),dataDir=path.join(root,'autopilot/data'),blog=path.join(root,'src/content/blog'),dist=path.join(root,'dist');fs.mkdirSync(blog,{recursive:true});fs.mkdirSync(path.join(dataDir,'runs'),{recursive:true});fs.mkdirSync(path.join(dist,'blog/article'),{recursive:true});fs.writeFileSync(path.join(root,'.gitignore'),'dist/\nautopilot/data/\n');fs.writeFileSync(path.join(blog,'article.md'),'released bytes');
 const git=(...args)=>{const r=spawnSync('git',args,{cwd:root,encoding:'utf8',env:{...process.env,GIT_AUTHOR_NAME:'test',GIT_AUTHOR_EMAIL:'test@example.test',GIT_COMMITTER_NAME:'test',GIT_COMMITTER_EMAIL:'test@example.test'}});assert.equal(r.status,0,r.stderr);return r.stdout.trim()};git('init','-q','-b','codex/publication-inputs');git('add','.');git('commit','-qm','release');const commit=git('rev-parse','HEAD');
 fs.writeFileSync(path.join(dataDir,'publish-log.json'),JSON.stringify({days:{'2026-10-06':['article']},kinds:{'2026-10-06':{article:'rewrite'}}}));const run={date:'2026-10-06',stages:{gated:{results:[{slug:'article',status:'published'}]},committed:{commit}}};fs.writeFileSync(path.join(dataDir,'runs/run.json'),JSON.stringify(run));fs.writeFileSync(path.join(dist,'release.json'),JSON.stringify({version:1,sourceClean:true,revision:commit}));fs.writeFileSync(path.join(dist,'blog/article/index.html'),'<article>released bytes</article>');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return{root,dataDir,dist,month:'2026-10',git,blog,run,commit};
}
test('publication proof inputs bind release manifest Git bytes and rendered hash',t=>{
 const f=fixture(t),r=publicationInputs(f);assert.equal(r.items.length,1);assert.equal(r.items[0].releaseCommit,f.commit);assert.equal(r.items[0].kind,'rewrite');assert.match(r.items[0].sourceSha256,/^[a-f0-9]{64}$/);assert.equal(r.items[0].expectedHtmlSha256,r.pages[0].expectedHtmlSha256);assert.equal(r.skipped.length,0);
});
test('a stale build cannot verify the current checkout',t=>{
 const f=fixture(t);fs.writeFileSync(path.join(f.dist,'release.json'),JSON.stringify({version:1,sourceClean:true,revision:'a'.repeat(40)}));assert.throws(()=>publicationInputs(f),/Build receipt/);
});
test('changed source and ambiguous manifests stay unverified instead of borrowing a receipt',t=>{
 const f=fixture(t);fs.writeFileSync(path.join(f.blog,'article.md'),'later content');f.git('commit','-qam','later version');fs.writeFileSync(path.join(f.dist,'release.json'),JSON.stringify({version:1,sourceClean:true,revision:f.git('rev-parse','HEAD')}));let r=publicationInputs(f);assert.equal(r.items.length,0);assert.equal(r.skipped[0].reason,'current-source-differs-from-released-version');fs.writeFileSync(path.join(f.dataDir,'runs/duplicate.json'),JSON.stringify(f.run));r=publicationInputs(f);assert.equal(r.skipped[0].reason,'release-manifest-missing-or-ambiguous');
});
