import "dotenv/config";
import path from "path";
import fs from "fs/promises";
import { generateBackground } from "./gemini.js";
import { renderTemplate } from "./render.js";
import {
  GEMINI_MODELS,
  BACKGROUND_STYLES,
  type BackgroundStyle,
  type ModelConfig,
} from "./types.js";

const OUTPUT_DIR = path.resolve("output");

// Controls which models and styles to generate.
// Reduce to avoid excessive API calls on first run.
const MODELS_TO_USE: ModelConfig[] = GEMINI_MODELS;
const STYLES_TO_USE: BackgroundStyle[] = BACKGROUND_STYLES;

async function run() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error(
      "GEMINI_API_KEY is not set. Create a .env file with GEMINI_API_KEY=<your-key>"
    );
  }

  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  console.log(
    `\nGenerating ${MODELS_TO_USE.length * STYLES_TO_USE.length} templates...\n`
  );
  console.log(
    `Models: ${MODELS_TO_USE.map((m) => m.displayName).join(", ")}`
  );
  console.log(`Styles: ${STYLES_TO_USE.join(", ")}\n`);

  const results: Array<{ model: string; style: string; file: string }> = [];
  const errors: Array<{ model: string; style: string; error: string }> = [];

  for (const model of MODELS_TO_USE) {
    console.log(`\n=== ${model.displayName} ===`);

    for (const style of STYLES_TO_USE) {
      try {
        const background = await generateBackground(apiKey, model, style);

        // Save raw SVG from Gemini for inspection
        const rawSvgPath = path.join(
          OUTPUT_DIR,
          `${model.name.replace(/[^a-z0-9]/gi, "-")}_${style}_raw.svg`
        );
        await fs.writeFile(rawSvgPath, background.svgContent);

        const pngPath = await renderTemplate(
          {
            title: `AI Background: ${style}`,
            subtitle: `Generated by ${model.displayName} · Rendered with Satori`,
            background,
          },
          OUTPUT_DIR
        );

        console.log(`  ✓ Saved: ${path.relative(process.cwd(), pngPath)}`);
        results.push({ model: model.name, style, file: pngPath });
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.error(`  ✗ Failed [${style}]: ${message}`);
        errors.push({ model: model.name, style, error: message });
      }

      // Small delay to avoid rate limiting
      await new Promise((r) => setTimeout(r, 500));
    }
  }

  // Write summary
  const summary = {
    generated: results.length,
    failed: errors.length,
    results,
    errors,
  };
  await fs.writeFile(
    path.join(OUTPUT_DIR, "summary.json"),
    JSON.stringify(summary, null, 2)
  );

  console.log(`\n${"=".repeat(50)}`);
  console.log(`Done! Generated: ${results.length}, Failed: ${errors.length}`);
  console.log(`Output: ${OUTPUT_DIR}`);
}

run().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});
